# Generated by Django 4.2.11 on 2024-03-14 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('type', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('code', models.CharField(max_length=128, verbose_name='code')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.material')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='warehouse.material')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='warehouse.product')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='product',
            field=models.ManyToManyField(through='warehouse.ProductMaterial', to='warehouse.product'),
        ),
    ]
