# Generated by Django 4.2.11 on 2024-03-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
    ]
